name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Check if commit message contains version
        id: check_version
        run: |
          if [[ "${{ steps.commit.outputs.message }}" =~ V[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
            echo "version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check_version.outputs.release == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        if: steps.check_version.outputs.release == 'true'
        run: |
          npm install tailwindcss
          npm ci

      - name: Run TailwindCSS CLI
        if: steps.check_version.outputs.release == 'true'
        run: npx tailwindcss -i ./src/input.css -o ./src/output.css

      - name: Package extension
        if: steps.check_version.outputs.release == 'true'
        run: |
          zip -r extension-${{ steps.check_version.outputs.version }}.zip src/* manifest.json

      - name: Create Release and Upload Asset
        if: steps.check_version.outputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check_version.outputs.version }}
          name: Release ${{ steps.check_version.outputs.version }}
          draft: false
          prerelease: false
          files: extension-${{ steps.check_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
