name: Release

on:
  release:
    types: [published]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Package extension
        run: |
          zip -r extension-v${{ github.event.release.tag_name }}.zip dist/* manifest.json

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./extension-v${{ github.event.release.tag_name }}.zip
          asset_name: extension-v${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
        if: success()

      - name: Update Release Description
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          body: |
            ## Chrome Extension v${{ github.event.release.tag_name }}
            
            ${{ github.event.release.body }}
            
            ### Installation
            1. Download the extension-v${{ github.event.release.tag_name }}.zip file
            2. Unzip the file
            3. Go to chrome://extensions/
            4. Enable Developer Mode
            5. Click "Load unpacked" and select the unzipped folder